---

# Travis file for owncloud role

dist: trusty
sudo: required

services:
  - docker

language: ruby
rvm:
  - 2.1.5

env:
  - ANSIBLE_ROLES_PATH="${TRAVIS_BUILD_DIR%/*/*}"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

  # Install ruby dependencies to run serverspec tests
  - rvmsudo gem install serverspec rspec

  # Install Ansible from devel, waiting 2.0 release. Install pytest also.
  - sudo pip install paramiko PyYAML Jinja2 httplib2 six pytest
  - git clone https://github.com/ansible/ansible.git ansible_clone
  - cd ansible_clone
    && git checkout v2.0.0-0.9.rc4
    && git submodule init
    && git submodule update
    && sudo make install
    && cd ..

  # Remove rvmsudo warning
  - "[[ $(sudo grep secure_path /etc/sudoers) ]]"
    && export rvmsudo_secure_path=1
    || export rvmsudo_secure_path=0

install:

  # Add ansible.cfg to pick up roles path.
  - "cp ./tests/ansible.cfg ./"

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test_travis.yml --syntax-check

  # Run filter plugins tests
  - py.test -v

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test_travis.yml --connection=local --sudo

  # Run the role/playbook again, checking to make sure it's idempotent.
  # Set change=1 due to a bug in ansible service module always return changed
  - >
    ansible-playbook -i tests/inventory tests/test_travis.yml --connection=local --sudo
    | grep -q 'changed=[0].*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Run serverspec tests
  - rvmsudo rspec

