---

# Owncloud configuration tasks

- name: Check if Owncloud already installed
  become: True
  become_user: "{{ item.user }}"
  stat:
    path: "{{ owncloud_www_directory }}/config/config.php"
  register: owncloud_check_installed
  with_items: owncloud_webserver_management
  when:
    - item.name == owncloud_webserver_name


- name: Configure owncloud after first installation
  become: True
  become_user: "{{ item.user }}"
  command: "php occ maintenance:install \
              --admin-user='{{ owncloud_administrator_user }}' \
              --admin-pass='{{ owncloud_administrator_password }}' \
              --database='{{ owncloud_database_engine }}' \
              --database-name='{{ owncloud_database_name }}' \
              --database-user='{{ owncloud_database_user }}' \
              --database-pass='{{
                  owncloud_database_password
                  or lookup(
                    'password',
                    '/tmp/' ~ owncloud_database_user ~ '_mysqlpassword') }}' \
              --data-dir='{{ owncloud_data_directory }}'"
  args:
    chdir: "{{ owncloud_www_directory }}"
  with_items: owncloud_webserver_management
  when:
    - item.name == owncloud_webserver_name
    - (owncloud_check_installed.results.0.stat.exists == False)
      or (owncloud_check_installed.results.0.stat.size == 0)


# TRUSTED DOMAIN MANAGEMENT : BEGIN
# Need to be done with this method, occ cannot set array in 8.2

- name: Get trusted domains
  become: True
  become_user: "{{ item.user }}"
  command: "php occ config:system:get trusted_domains"
  args:
    chdir: "{{ owncloud_www_directory }}"
  register: owncloud_check_trusted_domains
  changed_when: False
  with_items: owncloud_webserver_management
  when:
    - item.name == owncloud_webserver_name


- name: Delete trusted domains
  become: True
  become_user: "{{ item.user }}"
  command: "php occ config:system:delete trusted_domains"
  args:
    chdir: "{{ owncloud_www_directory }}"
  with_items: owncloud_webserver_management
  when:
    - item.name == owncloud_webserver_name
    - owncloud_check_trusted_domains.results.0.stdout_lines
        != owncloud_trusted_domains


- name: Configure trusted domains
  become: True
  blockinfile:
    dest: "{{ owncloud_www_directory }}/config/config.php"
    block: |
      {{ "'trusted_domains' =>" | indent(2, true) }}
      {{ "array(" | indent(2, true) }}
      {% for domain in owncloud_trusted_domains %}
        {{ (loop.index0 ~ " => '" ~ domain) | indent(2, true) ~ "'," }}
      {% endfor %}
      {{ ")," | indent(2, true) }}
    insertafter: "'secret' =>"
    marker: "{{ '/* Block managed by Ansible : {mark} */' | indent(2, true) }}"
  when:
    - owncloud_check_trusted_domains.results.0.stdout_lines
        != owncloud_trusted_domains

# TRUSTED DOMAIN MANAGEMENT : END


- name: Check if Owncloud already to latest version
  become: True
  become_user: "{{ item.user }}"
  shell: "php occ upgrade --dry-run | grep -c 'already latest version'"
  args:
    chdir: "{{ owncloud_www_directory }}"
  changed_when: False
  register: owncloud_check_upgrade
  with_items: owncloud_webserver_management
  when:
    - item.name == owncloud_webserver_name


- name: Upgrade owncloud if not latest version installed
  become: True
  become_user: "{{ item.user }}"
  command: "php occ upgrade"
  args:
    chdir: "{{ owncloud_www_directory }}"
  with_items: owncloud_webserver_management
  when:
    - item.name == owncloud_webserver_name
    - owncloud_check_upgrade.results.0.stdout != '1'

- name: Add debug about travis test failure
  become: True
  command: "cat /var/www/owncloud/config/config.php"
  register: travis_debug

- debug:
    var: travis_debug

